server:
  port: 81
spring:
  application:
    name: eshicha-email
  mail:
    host: smtp.163.com
    username: zhou999264@163.com
    password: KHEWFIHJTPRCBWQP
    send: 294424884@qq.com
    #send: zhou999264@qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true
          required: true
  redis:
    open: false  # 是否开启redis缓存  true开启   false关闭
    database: 1
    host: localhost
    port: 6379
    password: 123qwe@   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

  thymeleaf:
    cache: true   #关闭缓存